(function(){
'use strict';
const KEY='rallye_cap_qc_v4';
const MIN=6,MAX=12,MIN_INN=4,MAX_INN=9;
const POSITIONS=['1B','2B','3B','AC','L1','L2'];
const FIELD_POS=['1B','2B','3B','AC'];
const PITCH=new Set(['L1','L2']);
const LEGEND={ '1B':'Premier but','2B':'Deuxième but','3B':'Troisième but','AC':'Arrêt-court','L1':'Lanceur 1 🧢','L2':'Lanceur 2 🧢','B':'Banc','L':'Lanceurs 🧢'};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const escAttr=s=>esc(s).replace(/'/g,'&#39;');
const uid=()=>Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4);
let state=loadState();
let analysis=null, problems=new Map(), dragRow=null, dragCell=null, selectedRow=null, selectedCol=null, highlightPos=null, statSort={key:'order',dir:1}, matchIndex=0, touchStartX=0;
function defaults(){return{team:'',opp:'',date:'',place:'',side:'visiteur',fixed:true,innings:4,players:[],order:[],schedule:[],route:'equipe'}}
function safeState(raw){let d=defaults(), s=Object.assign(d, raw&&typeof raw==='object'?raw:{});s.team=String(s.team||'').slice(0,80);s.opp=String(s.opp||'').slice(0,80);s.date=String(s.date||'').slice(0,20);s.place=String(s.place||'').slice(0,120);s.side=s.side==='locale'?'locale':'visiteur';s.fixed=s.fixed!==false;s.innings=Math.min(MAX_INN,Math.max(MIN_INN,parseInt(s.innings||4,10)||4));let seen=new Set();s.players=(Array.isArray(s.players)?s.players:[]).slice(0,40).map(p=>({id:String(p.id||uid()),name:String(p.name||'').trim().slice(0,60),on:p.on!==false})).filter(p=>p.name&&!seen.has(p.id)&&seen.add(p.id));s.players=s.players.slice(0,24);let ids=new Set(s.players.map(p=>p.id));s.order=(Array.isArray(s.order)?s.order:[]).map(String).filter(id=>ids.has(id));s.players.forEach(p=>{if(!s.order.includes(p.id))s.order.push(p.id)});s.schedule=Array.isArray(s.schedule)?s.schedule.slice(0,s.innings):[];while(s.schedule.length<s.innings)s.schedule.push({pos:{}});s.schedule=s.schedule.map(inn=>{let pos={};if(inn&&inn.pos&&typeof inn.pos==='object'){Object.keys(inn.pos).slice(0,24).forEach(id=>{if(ids.has(id)){let v=String(inn.pos[id]||'');if(POSITIONS.includes(v))pos[id]=v}})}return{pos}});s.route=['equipe','ordre','alignement','match'].includes(s.route)?s.route:'equipe';return s}
function loadState(){try{return safeState(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return defaults()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function modal(title,text,buttons){$('#modalTitle').textContent=title;$('#modalText').textContent=text;let actions=$('#modalActions');actions.innerHTML='';(buttons||[{label:'OK',kind:'brandBtn'}]).forEach(b=>{let btn=document.createElement('button');btn.className='btn '+(b.kind||'secondary');btn.textContent=b.label;btn.onclick=()=>{closeModal();if(b.onClick)b.onClick()};actions.appendChild(btn)});$('#modalOverlay').classList.add('show')}
function closeModal(){$('#modalOverlay').classList.remove('show')}
function confirmModal(title,text,onYes){modal(title,text,[{label:'Annuler',kind:'secondary'},{label:'Confirmer',kind:'danger',onClick:onYes}])}
function player(id){return state.players.find(p=>p.id===id)}
function active(){let ids=new Set(state.players.filter(p=>p.on).map(p=>p.id));let arr=state.order.filter(id=>ids.has(id)).map(player).filter(Boolean);state.players.filter(p=>p.on&&!state.order.includes(p.id)).forEach(p=>arr.push(p));return arr.slice(0,MAX)}
function route(name){let r=name||location.hash.replace('#','')||state.route||'equipe';if(!['equipe','ordre','alignement','match'].includes(r))r='equipe';state.route=r;save();$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+r));$$('[data-nav],[data-step]').forEach(a=>a.classList.toggle('active',(a.dataset.nav||a.dataset.step)===r));$('#nav').classList.remove('open');if(r==='match')renderMatch();}
function updateFromInputs(){state.team=$('#team').value.trim();state.opp=$('#opp').value.trim();state.date=$('#date').value;state.place=$('#place').value.trim();state.fixed=$('#fixed').checked;save();}
function batters(inning){let a=active();if(!a.length)return[];if(!state.fixed)return a.map((p,i)=>({id:p.id,rank:i+1,name:p.name}));let start=(inning*6)%a.length;let out=[];for(let j=0;j<Math.min(6,a.length);j++){let idx=(start+j)%a.length;out.push({id:a[idx].id,rank:j+1,name:a[idx].name,global:idx+1})}return out}
function batterCounts(){let counts={};active().forEach(p=>counts[p.id]=0);if(state.fixed){for(let i=0;i<state.innings;i++)batters(i).forEach(b=>counts[b.id]++)}return counts}
function emptyStats(){return{ab:0,def:0,total:0,bench:0,pos:{'1B':0,'2B':0,'3B':0,'AC':0,'L1':0,'L2':0}}}
function collectStats(){let st={};active().forEach(p=>st[p.id]=emptyStats());let bc=batterCounts();Object.keys(bc).forEach(id=>{if(st[id])st[id].ab=bc[id]});state.schedule.forEach(inn=>{active().forEach(p=>{let po=inn.pos[p.id];if(po){st[p.id].def++;st[p.id].pos[po]=(st[p.id].pos[po]||0)+1}else st[p.id].bench++})});Object.values(st).forEach(s=>s.total=s.ab+s.def);return st}
function generatedPositionCounts(schedule){let st={};active().forEach(p=>st[p.id]=emptyStats());let bc=batterCounts();Object.keys(bc).forEach(id=>{if(st[id])st[id].ab=bc[id]});schedule.forEach(inn=>active().forEach(p=>{let po=inn.pos[p.id];if(po){st[p.id].def++;st[p.id].pos[po]=(st[p.id].pos[po]||0)+1}else st[p.id].bench++}));Object.values(st).forEach(s=>s.total=s.ab+s.def);return st}
function combinations(arr,k){let res=[];function rec(start,combo){if(combo.length===k){res.push(combo.slice());return}for(let i=start;i<=arr.length-(k-combo.length);i++){combo.push(arr[i]);rec(i+1,combo);combo.pop()}}rec(0,[]);return res}
function generateAll(){let a=active();if(a.length<MIN||a.length>MAX){modal('Alignement impossible','Il faut entre 6 et 12 joueurs actifs.');return}let sched=[];for(let i=0;i<state.innings;i++)sched.push(generateInning(i,sched));state.schedule=sched;save();renderAll()}
function appendInning(){if(state.innings>=MAX_INN){modal('Maximum atteint','Le maximum est de 9 manches.');return}state.innings++;state.schedule.push(generateInning(state.innings-1,state.schedule));save();renderAll()}
function removeInning(){if(state.innings<=MIN_INN){modal('Minimum atteint','Il faut conserver au moins 4 manches.');return}state.innings--;state.schedule.pop();save();renderAll()}
function generateInning(i,prior){let a=active(), ids=a.map(p=>p.id);let prev=prior[i-1];let prevBench=new Set();let prevPitch=new Set();if(prev){ids.forEach(id=>{let po=prev.pos[id];if(!po)prevBench.add(id);if(PITCH.has(po))prevPitch.add(id)})}let bset=new Set(state.fixed?batters(i).map(b=>b.id):[]);let st=generatedPositionCounts(prior);let combos=combinations(ids,Math.min(6,ids.length));let best=null,bestScore=Infinity;
  for(let combo of combos){let set=new Set(combo);let score=0;prevBench.forEach(id=>{if(!set.has(id))score+=100000});let nonBatIn=0;combo.forEach(id=>{if(!bset.has(id))nonBatIn++});score-=nonBatIn*30;combo.forEach(id=>{let s=st[id]||emptyStats();score+=s.def*7+s.total*4; if(bset.has(id))score+=2});let bench=ids.filter(id=>!set.has(id));bench.forEach(id=>{let s=st[id]||emptyStats();score+=s.bench*9; if((s.total||0) < averageTotal(st)) score+=4});if(score<bestScore){bestScore=score;best=combo}}
  let pos=assignPositions(best||ids.slice(0,6),prevPitch,st);return{pos}}
function averageTotal(st){let vals=Object.values(st);return vals.length?vals.reduce((a,b)=>a+b.total,0)/vals.length:0}
function assignPositions(defIds,prevPitch,st){let ids=defIds.slice();let pos={};let used=new Set();let scoreFor=id=>st[id]||emptyStats();let firstBaseCandidates=ids.filter(id=>(scoreFor(id).pos['1B']||0)===0);if(!firstBaseCandidates.length)firstBaseCandidates=ids.slice();firstBaseCandidates.sort((a,b)=>((scoreFor(a).pos['1B']||0)-(scoreFor(b).pos['1B']||0)) || (scoreFor(a).def-scoreFor(b).def) || (scoreFor(a).total-scoreFor(b).total));let one=firstBaseCandidates[0];pos[one]='1B';used.add(one);
  let pitcherCandidates=ids.filter(id=>!used.has(id)&&!prevPitch.has(id));if(pitcherCandidates.length<2)pitcherCandidates=ids.filter(id=>!used.has(id));pitcherCandidates.sort((a,b)=>{let sa=scoreFor(a),sb=scoreFor(b);let va=(sa.pos['1B']||0)*8+(sa.pos['L1']||0)+(sa.pos['L2']||0)*1.2+sa.def*.4+sa.total*.2;let vb=(sb.pos['1B']||0)*8+(sb.pos['L1']||0)+(sb.pos['L2']||0)*1.2+sb.def*.4+sb.total*.2;return va-vb});let p1=pitcherCandidates[0],p2=pitcherCandidates.find(id=>id!==p1);if(p1){pos[p1]='L1';used.add(p1)}if(p2){pos[p2]='L2';used.add(p2)}
  let rest=ids.filter(id=>!used.has(id));let spots=['2B','3B','AC'];spots.forEach(sp=>{if(!rest.length)return;rest.sort((a,b)=>((scoreFor(a).pos[sp]||0)-(scoreFor(b).pos[sp]||0)) || (scoreFor(a).def-scoreFor(b).def) || a.localeCompare(b));let id=rest.shift();pos[id]=sp;used.add(id)});
  rest.forEach(id=>{let free=POSITIONS.find(p=>!Object.values(pos).includes(p));if(free)pos[id]=free});return pos}
function ensureSchedule(){let a=active();let ids=new Set(a.map(p=>p.id));state.schedule=state.schedule.slice(0,state.innings);while(state.schedule.length<state.innings)state.schedule.push({pos:{}});state.schedule.forEach((inn,i)=>{let cleaned={};Object.entries(inn.pos||{}).forEach(([id,po])=>{if(ids.has(id)&&POSITIONS.includes(po))cleaned[id]=po});inn.pos=cleaned;let count=Object.keys(cleaned).length;if(a.length>=MIN&&(count!==6||new Set(Object.values(cleaned)).size!==count)){state.schedule[i]=generateInning(i,state.schedule.slice(0,i))}})}
function analyze(){ensureSchedule();problems=new Map();let vals=[],sugs=[],ids=active().map(p=>p.id);let st=collectStats();let mark=(id,i,msg)=>{let k=id+':'+i;if(!problems.has(k))problems.set(k,[]);problems.get(k).push(msg)};let pname=id=>player(id)?.name||'Joueur';
  let defenseOk=true;state.schedule.forEach((inn,i)=>{let c=Object.keys(inn.pos||{}).filter(id=>ids.includes(id)).length;if(c!==Math.min(6,ids.length)){defenseOk=false;ids.forEach(id=>mark(id,i,'La manche n’a pas exactement 6 défenseurs'))}});vals.push({ok:defenseOk,text:defenseOk?'Chaque manche a exactement 6 défenseurs.':'Une manche n’a pas exactement 6 défenseurs.'});
  let bench=[];ids.forEach(id=>{for(let i=1;i<state.schedule.length;i++){let a=!state.schedule[i-1].pos[id],b=!state.schedule[i].pos[id];if(a&&b){bench.push({id,i});mark(id,i-1,'Banc deux manches de suite');mark(id,i,'Banc deux manches de suite')}}});vals.push({ok:!bench.length,text:!bench.length?'Aucun joueur au banc deux manches consécutives.':'Un joueur est au banc deux manches consécutives.'});bench.slice(0,5).forEach(x=>sugs.push(makeBenchSuggestion(x.id,x.i)));
  let one=[];ids.forEach(id=>{let ins=[];state.schedule.forEach((inn,i)=>{if(inn.pos[id]==='1B')ins.push(i)});if(ins.length>1){one.push({id,ins});ins.forEach(i=>mark(id,i,'Premier but plus d’une fois'))}});vals.push({ok:!one.length,text:!one.length?'Chaque joueur est 1B au maximum une fois.':'Un joueur joue 1B plus d’une fois.'});if(state.innings>ids.length)vals.push({ok:false,warn:true,text:'Premier but unique mathématiquement impossible: '+state.innings+' manches pour '+ids.length+' joueurs.'});one.slice(0,5).forEach(x=>sugs.push(makeFirstBaseSuggestion(x.id,x.ins)));
  let pit=[];ids.forEach(id=>{for(let i=1;i<state.schedule.length;i++){let a=state.schedule[i-1].pos[id],b=state.schedule[i].pos[id];if(PITCH.has(a)&&PITCH.has(b)){pit.push({id,i});mark(id,i-1,'Lanceur deux manches de suite');mark(id,i,'Lanceur deux manches de suite')}}});vals.push({ok:!pit.length,text:!pit.length?'Aucun joueur n’est lanceur deux manches consécutives.':'Un joueur est lanceur deux manches consécutives.'});pit.slice(0,5).forEach(x=>sugs.push(makePitchSuggestion(x.id,x.i)));
  let f=fairness(st);if(state.fixed)vals.push({ok:f.abGap<=1,text:f.abGap<=1?'Présences au bâton équilibrées (écart ≤ 1).':'Présences au bâton moins équilibrées (écart '+f.abGap+').'});else vals.push({ok:true,warn:true,text:'Frappe fixe désactivée: les présences au bâton par manche ne sont pas calculées.'});vals.push({ok:f.totalGap<=1||ids.length===6,warn:f.totalGap>1&&ids.length!==6,text:(f.totalGap<=1||ids.length===6)?'Temps de jeu total très équilibré.':'Temps de jeu total à surveiller (écart '+f.totalGap+').'});
  sugs=sugs.filter(Boolean);if(!sugs.length)sugs.push({level:'ok',title:'Aucun problème majeur détecté',text:'Les règles sont respectées. Tu peux imprimer ou exporter.',action:null});analysis={validations:vals,suggestions:sugs,stats:st,fair:f,rulesOk:vals.filter(v=>!v.warn).every(v=>v.ok)};return analysis}
function fairness(st){let v=Object.values(st);if(!v.length)return{abGap:0,defGap:0,totalGap:0,posGap:0,overall:0,abScore:0,defScore:0,totalScore:0,posScore:0};let gap=a=>Math.max(...a)-Math.min(...a);let abGap=gap(v.map(x=>x.ab)),defGap=gap(v.map(x=>x.def)),totalGap=gap(v.map(x=>x.total));let all=[];v.forEach(x=>POSITIONS.forEach(p=>all.push(x.pos[p]||0)));let posGap=gap(all);let sc=(g,ideal)=>g<=ideal?100:Math.max(0,Math.round(100-(g-ideal)*18));let abScore=sc(abGap,1),defScore=sc(defGap,2),totalScore=sc(totalGap,1),posScore=sc(posGap,3);let overall=Math.round(abScore*.34+totalScore*.34+defScore*.22+posScore*.10);return{abGap,defGap,totalGap,posGap,overall,abScore,defScore,totalScore,posScore}}
function makeFirstBaseSuggestion(id,ins){let inning=ins[1];let target=active().map(p=>p.id).find(other=>other!==id&&state.schedule[inning].pos[other]&&state.schedule[inning].pos[other]!=='1B'&&!hasPlayed(other,'1B',inning));return{level:'bad',title:player(id).name+' joue 1B plus d’une fois',text:target?'Échanger '+player(id).name+' (1B) avec '+player(target).name+' ('+state.schedule[inning].pos[target]+') à la manche '+(inning+1)+'.':'Aucune correction simple trouvée automatiquement.',action:target?{type:'swap',inning,id,target}:null}}
function makePitchSuggestion(id,inning){let target=active().map(p=>p.id).find(other=>other!==id&&state.schedule[inning].pos[other]&&!PITCH.has(state.schedule[inning].pos[other])&&!wasPitcher(other,inning-1)&&!willBePitcher(other,inning+1));return{level:'bad',title:player(id).name+' est lanceur deux manches de suite',text:target?'Échanger '+player(id).name+' ('+state.schedule[inning].pos[id]+') avec '+player(target).name+' ('+state.schedule[inning].pos[target]+') à la manche '+(inning+1)+'.':'Aucune correction simple trouvée automatiquement.',action:target?{type:'swap',inning,id,target}:null}}
function makeBenchSuggestion(id,inning){let target=active().map(p=>p.id).find(other=>state.schedule[inning].pos[other]&&!wouldBenchBreak(other,inning));return{level:'bad',title:player(id).name+' est au banc deux manches de suite',text:target?'Donner la position de '+player(target).name+' à '+player(id).name+' à la manche '+(inning+1)+', et mettre '+player(target).name+' au banc.':'Aucune correction simple trouvée automatiquement.',action:target?{type:'benchswap',inning,id,target}:null}}
function hasPlayed(id,pos,except){return state.schedule.some((inn,i)=>i!==except&&inn.pos[id]===pos)}
function wasPitcher(id,i){return i>=0&&PITCH.has(state.schedule[i]?.pos[id])}
function willBePitcher(id,i){return i<state.schedule.length&&PITCH.has(state.schedule[i]?.pos[id])}
function wouldBenchBreak(id,i){return (i>0&&!state.schedule[i-1].pos[id])||(i<state.schedule.length-1&&!state.schedule[i+1].pos[id])}
function applySuggestion(action){if(!action)return;if(action.type==='swap'){let pos=state.schedule[action.inning].pos,p1=pos[action.id],p2=pos[action.target];pos[action.id]=p2;pos[action.target]=p1}else if(action.type==='benchswap'){let pos=state.schedule[action.inning].pos;pos[action.id]=pos[action.target];delete pos[action.target]}save();renderAll()}
function renderAll(){analysis=null;renderInputs();renderPlayers();renderOrder();renderAlign();renderMatch();renderMini();route()}
function renderInputs(){$('#team').value=state.team;$('#opp').value=state.opp;$('#date').value=state.date;$('#place').value=state.place;$('#fixed').checked=state.fixed;$$('[data-side]').forEach(b=>b.classList.toggle('active',b.dataset.side===state.side))}
function renderMini(){let a=active().length;$('#miniPlayers').textContent=a;$('#miniInnings').textContent=state.innings;$('#miniSide').textContent=state.side==='locale'?'Loc.':'Vis.';let f=(analysis||analyze()).fair;$('#miniScore').textContent=a>=MIN?f.overall+'%':'—';$('#activeCountTag').textContent=a+' actif'+(a>1?'s':'')}
function renderPlayers(){let w=$('#players');if(!state.players.length){w.innerHTML='<div class="empty">Aucun joueur enregistré. Ajoute ou colle des noms ci-dessous.</div>';return}w.innerHTML=state.players.map(p=>'<div class="pill '+(p.on?'activeCard':'off')+'"><button class="pname" data-toggle="'+p.id+'">'+esc(p.name)+'</button><div class="row" style="gap:6px"><button class="icon '+(p.on?'active':'soft')+'" data-toggle="'+p.id+'" title="Activer/désactiver">'+(p.on?'✓':'')+'</button><button class="icon soft" data-delete="'+p.id+'" title="Supprimer">✕</button></div></div>').join('');$$('[data-toggle]').forEach(b=>b.onclick=()=>{let pl=player(b.dataset.toggle);if(pl){pl.on=!pl.on;save();renderAll()}});$$('[data-delete]').forEach(b=>b.onclick=()=>{let pl=player(b.dataset.delete);if(pl)confirmModal('Supprimer un joueur','Supprimer '+pl.name+' de la liste enregistrée?',()=>{state.players=state.players.filter(x=>x.id!==pl.id);state.order=state.order.filter(id=>id!==pl.id);state.schedule.forEach(inn=>delete inn.pos[pl.id]);save();renderAll()})})}
function renderOrder(){let a=active(),w=$('#orderAlerts'),o=$('#order'),errs=[];if(a.length<MIN)errs.push('Il faut au moins '+MIN+' joueurs actifs.');if(a.length>MAX)errs.push('Il faut au maximum '+MAX+' joueurs actifs.');w.innerHTML=errs.length?errs.map(e=>'<div class="alert bad"><span class="mark">✖</span><div>'+esc(e)+'</div></div>').join(''):'<div class="alert ok"><span class="mark">✔</span><div>'+a.length+' joueurs actifs.</div></div>';o.innerHTML=a.length?a.map((p,i)=>'<div class="orderRow" draggable="true" data-row="'+p.id+'"><div class="rank">'+(i+1)+'</div><b>'+esc(p.name)+'</b><div class="grab">⋮⋮</div></div>').join(''):'<div class="empty">Active des joueurs à l’étape 1.</div>';dndRows(o)}
function renderAlign(){let a=active();if(a.length<MIN||a.length>MAX){$('#validations').innerHTML='<div class="alert bad"><span class="mark">✖</span><div>Active entre '+MIN+' et '+MAX+' joueurs.</div></div>';$('#lineup').innerHTML='<div class="empty">Pas encore prêt.</div>';$('#scores').innerHTML='';$('#suggestions').innerHTML='';$('#stats').innerHTML='';$('#field').innerHTML='';$('#legend').innerHTML='';return}let an=analyze();$('#validations').innerHTML=an.validations.map(v=>'<div class="alert '+(v.ok?'ok':v.warn?'warn':'bad')+'"><span class="mark">'+(v.ok?'✔':v.warn?'⚠':'✖')+'</span><div>'+esc(v.text)+'</div></div>').join('');let f=an.fair;$('#scores').innerHTML=[['Présences au bâton',f.abScore,'Écart max: '+f.abGap],['Temps de jeu total',f.totalScore,'Écart max: '+f.totalGap],['Défensive',f.defScore,'Écart max: '+f.defGap],['Indice global',f.overall,f.overall>=92?'Excellent':f.overall>=80?'Bon':'À améliorer']].map(x=>'<div class="score"><span class="label">'+esc(x[0])+'</span><strong>'+x[1]+'%</strong><div class="hint">'+esc(x[2])+'</div></div>').join('');renderTable();renderSuggestions(an.suggestions);renderStats(an.stats);renderField();renderLegend()}
function renderTable(){let a=active(),rankMaps=[];for(let i=0;i<state.innings;i++)rankMaps.push(new Map(batters(i).map(b=>[b.id,b.rank])));let h='<table><thead><tr><th>Ordre</th>';for(let i=0;i<state.innings;i++){h+='<th data-head="'+i+'" class="'+(selectedCol===i?'colSelected':'')+'">Manche '+(i+1);if(i===state.innings-1){h+='<div class="row" style="justify-content:center;margin-top:6px"><button class="icon soft" data-remove-inning title="Retirer une manche">−</button><button class="icon soft" data-add-inning title="Ajouter une manche">+</button></div>'}h+='</th>'}h+='</tr></thead><tbody>';a.forEach((pl,ri)=>{h+='<tr data-tr="'+pl.id+'"><td class="playerCell '+(selectedRow===pl.id?'rowSelected':'')+'" draggable="true" data-row="'+pl.id+'"><div class="pin"><span class="rank">'+(ri+1)+'</span><b>'+esc(pl.name)+'</b></div></td>';for(let i=0;i<state.innings;i++){let po=state.schedule[i]?.pos[pl.id]||'B',r=rankMaps[i].get(pl.id),bad=problems.get(pl.id+':'+i),lab=(po==='B'?'BANC':po)+(r?' (#'+r+')':'');let hi=(highlightPos&&(highlightPos===po||(highlightPos==='L'&&PITCH.has(po))))?'posHighlight':'';h+='<td class="'+(selectedCol===i?'colSelected':'')+'"><span class="cell '+(po==='B'?'bench ':'')+(bad?'problem ':'')+hi+'" draggable="true" title="'+escAttr(bad?bad.join(' · '):pl.name)+'" data-cell="'+pl.id+'" data-inning="'+i+'" data-pos="'+po+'">'+esc(lab)+'</span></td>'}h+='</tr>'});h+='</tbody></table>';$('#lineup').innerHTML=h;dndRows($('#lineup'));dndCells();$$('[data-head]').forEach(th=>th.onclick=e=>{if(e.target.closest('button'))return;selectedCol=+th.dataset.head;selectedRow=null;renderTable()});$$('.playerCell').forEach(td=>td.onclick=e=>{selectedRow=td.dataset.row;selectedCol=null;renderTable()});$$('.cell').forEach(c=>c.onclick=e=>{selectedRow=c.dataset.cell;selectedCol=+c.dataset.inning;renderTable()});$('[data-add-inning]')?.addEventListener('click',e=>{e.stopPropagation();appendInning()});$('[data-remove-inning]')?.addEventListener('click',e=>{e.stopPropagation();removeInning()})}
function dndRows(root){root.querySelectorAll('[data-row]').forEach(el=>{el.ondragstart=e=>{dragRow=el.dataset.row;dragCell=null;el.classList.add('dragging');e.dataTransfer.effectAllowed='move'};el.ondragend=()=>{el.classList.remove('dragging');dragRow=null};el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();let target=el.dataset.row;if(dragRow&&target&&dragRow!==target){let arr=state.order,from=arr.indexOf(dragRow),to=arr.indexOf(target);if(from>=0&&to>=0){let m=arr.splice(from,1)[0];arr.splice(to,0,m);save();renderAll()}}}})}
function dndCells(){$$('#lineup .cell').forEach(el=>{el.ondragstart=e=>{dragCell={id:el.dataset.cell,i:+el.dataset.inning};dragRow=null;el.classList.add('dragging');e.dataTransfer.effectAllowed='move'};el.ondragend=()=>{el.classList.remove('dragging');$$('.cell').forEach(c=>c.classList.remove('over'));dragCell=null};el.ondragover=e=>{if(dragCell&&+el.dataset.inning===dragCell.i){e.preventDefault();el.classList.add('over')}};el.ondragleave=()=>el.classList.remove('over');el.ondrop=e=>{e.preventDefault();el.classList.remove('over');if(!dragCell)return;let id2=el.dataset.cell,i=+el.dataset.inning;if(i!==dragCell.i||id2===dragCell.id)return;let pos=state.schedule[i].pos,p1=pos[dragCell.id],p2=pos[id2];if(p1)pos[id2]=p1;else delete pos[id2];if(p2)pos[dragCell.id]=p2;else delete pos[dragCell.id];save();renderAll()}})}
function renderLegend(){let items=[['1B','Premier but'],['2B','Deuxième but'],['3B','Troisième but'],['AC','Arrêt-court'],['L','Lanceurs 🧢'],['B','Banc'],['#','Rang de frappe dans la manche']];$('#legend').innerHTML=items.map(([k,v])=>'<button class="tag clickable '+(highlightPos===k?'active':'')+'" data-legend="'+k+'"><b>'+esc(k)+'</b> = '+esc(v)+'</button>').join('');$$('[data-legend]').forEach(b=>b.onclick=()=>{highlightPos=highlightPos===b.dataset.legend?null:b.dataset.legend;renderTable();renderLegend()})}
function renderSuggestions(sugs){$('#suggestions').innerHTML=sugs.map((s,i)=>'<div class="suggestion"><div><b>'+(s.level==='bad'?'❌':s.level==='warn'?'⚠':'✔')+' '+esc(s.title)+'</b><div class="hint">'+esc(s.text)+'</div></div>'+(s.action?'<button class="btn secondary" data-apply="'+i+'">Appliquer</button>':'')+'</div>').join('');$$('[data-apply]').forEach(b=>b.onclick=()=>applySuggestion(analysis.suggestions[+b.dataset.apply].action))}
function renderStats(st){let rows=active().map((pl,i)=>({id:pl.id,name:pl.name,order:i+1,...(st[pl.id]||emptyStats())}));let key=statSort.key,dir=statSort.dir;rows.sort((a,b)=>{let va=key==='name'?a.name.toLowerCase():a[key],vb=key==='name'?b.name.toLowerCase():b[key];if(key==='order')return (a.order-b.order)*dir;if(va<vb)return -1*dir;if(va>vb)return 1*dir;return a.order-b.order});let headers=[['name','Joueur'],['order','Ordre'],['ab','AB'],['def','Déf.'],['total','Total'],['bench','Banc'],['one','1B'],['two','2B'],['three','3B'],['ac','AC'],['pitch','L']];let h='<table class="statSort"><thead><tr>'+headers.map(x=>'<th><button data-sort="'+x[0]+'">'+x[1]+(statSort.key===x[0]?(statSort.dir>0?' ▲':' ▼'):'')+'</button></th>').join('')+'</tr></thead><tbody>';rows.forEach(r=>{h+='<tr><td style="text-align:left"><b>'+esc(r.name)+'</b></td><td>'+r.order+'</td><td>'+r.ab+'</td><td>'+r.def+'</td><td>'+r.total+'</td><td>'+r.bench+'</td><td>'+(r.pos['1B']||0)+'</td><td>'+(r.pos['2B']||0)+'</td><td>'+(r.pos['3B']||0)+'</td><td>'+(r.pos['AC']||0)+'</td><td>'+((r.pos['L1']||0)+(r.pos['L2']||0))+'</td></tr>'});$('#stats').innerHTML=h+'</tbody></table>';$$('[data-sort]').forEach(b=>b.onclick=()=>{let k=b.dataset.sort;if(statSort.key===k)statSort.dir*=-1;else{statSort.key=k;statSort.dir=1}renderStats(analysis.stats)})}
function renderField(){let by={'1B':[],'2B':[],'3B':[],'AC':[],L:[]};state.schedule.forEach((inn,i)=>{let rev={};Object.entries(inn.pos||{}).forEach(([id,po])=>rev[po]=id);by['1B'].push(pname(rev['1B']));by['2B'].push(pname(rev['2B']));by['3B'].push(pname(rev['3B']));by['AC'].push(pname(rev['AC']));by.L.push((pname(rev['L1'])||'—')+' - '+(pname(rev['L2'])||'—'))});function list(arr){return '<ol>'+arr.map(x=>'<li>'+esc(x||'—')+'</li>').join('')+'</ol>'}$('#field').innerHTML='<div class="diamond"></div><div class="posBox pos-2B"><h4>2B — Deuxième but</h4>'+list(by['2B'])+'</div><div class="posBox pos-AC"><h4>AC — Arrêt-court</h4>'+list(by['AC'])+'</div><div class="posBox pos-L"><h4>Lanceurs 🧢</h4>'+list(by.L)+'</div><div class="posBox pos-3B"><h4>3B — Troisième but</h4>'+list(by['3B'])+'</div><div class="posBox pos-1B"><h4>1B — Premier but</h4>'+list(by['1B'])+'</div>'}
function pname(id){return id?(player(id)?.name||'—'):'—'}
function matchPhases(){let phases=[];for(let i=0;i<state.innings;i++){['debut','fin'].forEach(half=>{let batting=(state.side==='visiteur'&&half==='debut')||(state.side==='locale'&&half==='fin');phases.push({inning:i,half,label:(half==='debut'?'Début':'Fin')+' de '+ordinal(i+1),type:batting?'attaque':'defense'})})}return phases}
function ordinal(n){return n===1?'1re':n+'e'}
function renderMatch(){let phases=matchPhases();if(matchIndex>=phases.length)matchIndex=phases.length-1;if(matchIndex<0)matchIndex=0;let ph=phases[matchIndex]||{label:'—',type:'attaque',inning:0};let title=ph.type==='attaque'?'À la frappe':'En défensive';let body=ph.type==='attaque'?renderMatchBatters(ph.inning):renderMatchDefense(ph.inning);$('#matchCard').innerHTML='<div><span class="matchPill">'+esc(ph.label)+' • '+(ph.type==='attaque'?'Attaque':'Défense')+'</span><h2 class="matchTitle">'+esc(title)+'</h2><div class="tiny" style="color:#dbeafe;margin-top:8px">'+esc(matchHeaderText())+'</div></div><div class="matchList">'+body+'</div>';
  $('#matchDots').innerHTML=phases.map((_,i)=>'<span class="dot '+(i===matchIndex?'active':'')+'"></span>').join('');$('#matchPrev').disabled=matchIndex<=0;$('#matchNext').disabled=matchIndex>=phases.length-1}
function renderMatchBatters(inning){let bs=batters(inning);if(!state.fixed)bs=active().map((p,i)=>({name:p.name,rank:i+1,id:p.id}));return bs.map(b=>'<div class="matchItem"><strong>'+b.rank+'. '+esc(b.name)+'</strong><span>Frappeur</span></div>').join('')}
function renderMatchDefense(inning){let inn=state.schedule[inning]||{pos:{}};let rev={};Object.entries(inn.pos||{}).forEach(([id,po])=>rev[po]=id);let rows=[['Lanceurs 🧢',(pname(rev.L1)||'—')+' - '+(pname(rev.L2)||'—')],['1B',pname(rev['1B'])],['2B',pname(rev['2B'])],['3B',pname(rev['3B'])],['AC',pname(rev['AC'])]];return rows.map(r=>'<div class="matchItem"><strong>'+esc(r[0])+'</strong><span>'+esc(r[1])+'</span></div>').join('')}
function matchHeaderText(){let t=state.team||'Équipe';let o=state.opp?' vs '+state.opp:'';let d=state.date?' • '+formatDate(state.date):'';let p=state.place?' • '+state.place:'';return t+o+d+p}
function formatDate(d){try{return new Date(d+'T12:00:00').toLocaleDateString('fr-CA',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}catch(e){return d}}
function setMatchIndex(i){matchIndex=Math.min(Math.max(0,i),matchPhases().length-1);renderMatch()}
function exportMatchHtml(){let data={team:state.team,opp:state.opp,date:state.date,place:state.place,side:state.side,phases:matchPhases().map(ph=>({label:ph.label,type:ph.type,title:ph.type==='attaque'?'À la frappe':'En défensive',items:(ph.type==='attaque'?batters(ph.inning).map(b=>[b.rank+'. '+b.name,'Frappeur']):defenseItems(ph.inning))}))};let html='<!doctype html><html lang="fr-CA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mode match - '+esc(data.team||'Rallye-Cap')+'</title><style>'+standaloneMatchCss()+'</style></head><body><main><section class="top"><div class="ball">⚾</div><div><h1>'+esc(data.team||'Équipe')+(data.opp?' <span>vs</span> '+esc(data.opp):'')+'</h1><p>'+esc((data.date?formatDate(data.date):'')+(data.place?' • '+data.place:''))+'</p></div></section><section class="card" id="card"></section><div class="dots" id="dots"></div><div class="nav"><button id="prev">←</button><button id="next">→</button></div><p class="help">Swipe gauche/droite pour avancer ou reculer.</p></main><script>const DATA='+JSON.stringify(data).replace(/</g,'\\u003c')+';let i=0;const $=s=>document.querySelector(s);function e(s){return String(s||"").replace(/[&<>\\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\\\"":"&quot;"}[c]))}function render(){let p=DATA.phases[i];$("#card").innerHTML=`<div class="pill">${e(p.label)} • ${p.type==="attaque"?"Attaque":"Défense"}</div><h2>${e(p.title)}</h2><div class="list">${p.items.map(x=>`<div class="item"><b>${e(x[0])}</b><span>${e(x[1])}</span></div>`).join("")}</div>`;$("#dots").innerHTML=DATA.phases.map((_,n)=>`<span class="dot ${n===i?"active":""}"></span>`).join("");$("#prev").disabled=i<=0;$("#next").disabled=i>=DATA.phases.length-1}function go(n){i=Math.max(0,Math.min(DATA.phases.length-1,i+n));render()}$("#prev").onclick=()=>go(-1);$("#next").onclick=()=>go(1);let sx=0;document.body.addEventListener("touchstart",ev=>sx=ev.touches[0].clientX,{passive:true});document.body.addEventListener("touchend",ev=>{let dx=ev.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)go(dx<0?1:-1)},{passive:true});addEventListener("keydown",ev=>{if(ev.key==="ArrowRight")go(1);if(ev.key==="ArrowLeft")go(-1)});render();<\/script></body></html>';downloadFile('mode-match-rallye-cap.html',html,'text/html;charset=utf-8');modal('Mode match exporté','Le fichier HTML autonome a été téléchargé. Tu peux l’envoyer aux autres entraîneurs ou parents.')}
function defenseItems(inning){let inn=state.schedule[inning]||{pos:{}};let rev={};Object.entries(inn.pos||{}).forEach(([id,po])=>rev[po]=id);return[['Lanceurs 🧢',(pname(rev.L1)||'—')+' - '+(pname(rev.L2)||'—')],['1B',pname(rev['1B'])],['2B',pname(rev['2B'])],['3B',pname(rev['3B'])],['AC',pname(rev['AC'])]]}
function standaloneMatchCss(){return 'body{margin:0;background:linear-gradient(180deg,#eef7ff,#f7fbff);font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#142033}main{max-width:760px;margin:auto;padding:18px}.top{display:flex;gap:14px;align-items:center;margin:8px 0 18px}.ball{width:54px;height:54px;border-radius:20px;background:linear-gradient(135deg,#0f7a4b,#23a261);display:grid;place-items:center;color:white;font-size:30px}h1{font-size:clamp(26px,7vw,44px);line-height:1;margin:0;letter-spacing:-.04em}h1 span{color:#64748b;font-size:.65em}p{color:#64748b}.card{background:linear-gradient(155deg,#122033,#1f3a56);color:white;border-radius:30px;box-shadow:0 24px 60px #0f172a33;padding:24px;min-height:430px}.pill{display:inline-flex;background:#ffffff1f;border:1px solid #ffffff30;border-radius:999px;padding:9px 12px;font-weight:900}.card h2{font-size:clamp(44px,11vw,76px);letter-spacing:-.06em;line-height:.9;margin:18px 0}.list{display:grid;gap:10px}.item{display:flex;justify-content:space-between;gap:12px;background:#ffffff1f;border:1px solid #ffffff2e;border-radius:18px;padding:13px 14px}.item b{font-size:18px}.item span{color:#dbeafe}.nav{display:flex;gap:12px;margin:14px 0}.nav button{flex:1;border:0;border-radius:16px;background:#142033;color:white;font-size:24px;font-weight:900;padding:14px}.nav button:disabled{opacity:.35}.dots{display:flex;justify-content:center;gap:6px;margin:14px}.dot{width:8px;height:8px;border-radius:50%;background:#cbd5e1}.dot.active{background:#0f7a4b}.help{text-align:center;font-size:13px}'}
function parentProgramSvg(){let a=active();let width=1200;let inningRows=state.fixed?state.innings:0;let height=Math.max(1700,620+a.length*42+inningRows*76+state.innings*64);let y=0;let s=[];let add=t=>s.push(t);let text=(x,y,txt,size=28,weight=700,fill='#162033')=>add('<text x="'+x+'" y="'+y+'" font-size="'+size+'" font-family="Arial, Helvetica, sans-serif" font-weight="'+weight+'" fill="'+fill+'">'+xml(txt)+'</text>');add('<svg xmlns="http://www.w3.org/2000/svg" width="'+width+'" height="'+height+'" viewBox="0 0 '+width+' '+height+'"><rect width="100%" height="100%" fill="#f7fbff"/><rect x="40" y="40" width="1120" height="'+(height-80)+'" rx="42" fill="#ffffff" stroke="#dbe5ef"/>');add('<rect x="40" y="40" width="1120" height="260" rx="42" fill="#0f7a4b"/>');text(90,130,'⚾ Programme de match',34,900,'#dfffea');text(90,205,state.team||'Équipe',64,900,'#ffffff');text(90,260,(state.opp?'vs '+state.opp:'')+(state.side==='locale'?' • Locale':' • Visiteur'),30,800,'#dfffea');text(760,205,state.date?formatDate(state.date):'',28,800,'#ffffff');text(760,250,state.place||'',24,700,'#dfffea');y=360;text(90,y,'Ordre des frappeurs',36,900);y+=44;a.forEach((p,i)=>{text(110,y,(i+1)+'. '+p.name,26,700);y+=38});if(state.fixed){y+=30;text(90,y,'Frappe par manche',36,900);y+=44;for(let i=0;i<state.innings;i++){let names=batters(i).map(b=>b.rank+'. '+b.name).join('   ');add('<rect x="90" y="'+(y-30)+'" width="1020" height="50" rx="18" fill="'+(i%2?'#f1f6fb':'#e8f6ef')+'"/>');text(115,y,'Manche '+(i+1),22,900,'#0f7a4b');text(260,y,names,22,700,'#162033');y+=62}}y+=20;text(90,y,'Défensive par manche',36,900);y+=50;for(let i=0;i<state.innings;i++){let items=defenseItems(i);add('<rect x="90" y="'+(y-32)+'" width="1020" height="56" rx="18" fill="#f8fafc" stroke="#dbe5ef"/>');text(115,y,''+(i+1)+'.',24,900,'#0f7a4b');text(165,y,'Lanceurs 🧢 '+items[0][1],23,800);text(520,y,'1B '+items[1][1]+'  •  2B '+items[2][1],22,700);text(835,y,'3B '+items[3][1]+'  •  AC '+items[4][1],22,700);y+=68}text(90,height-110,'Légende: L1/L2 = Lanceurs 🧢 • AC = Arrêt-court • 1B/2B/3B = buts',22,700,'#617086');add('</svg>');return s.join('')}
function exportParentImage(){let svg=parentProgramSvg();let img=new Image();let url='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);img.onload=function(){let canvas=document.createElement('canvas');canvas.width=img.width*2;canvas.height=img.height*2;let ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(blob)downloadBlob('programme-parents-rallye-cap.png',blob);else downloadFile('programme-parents-rallye-cap.svg',svg,'image/svg+xml')},'image/png',0.96)};img.onerror=()=>downloadFile('programme-parents-rallye-cap.svg',svg,'image/svg+xml');img.src=url}
function xml(s){return String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function printCoach(){let html='<html><head><title>Alignement</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#111}h1{margin-bottom:0}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #111;padding:6px;text-align:center}th:first-child,td:first-child{text-align:left}.legend{margin-top:12px}.fieldGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.box{border:1px solid #111;padding:10px;border-radius:8px}li{margin:4px 0}@media print{button{display:none}}</style></head><body><button onclick="print()">Imprimer / Enregistrer en PDF</button><h1>'+esc(state.team||'Équipe')+(state.opp?' vs '+esc(state.opp):'')+'</h1><p>'+esc((state.date?formatDate(state.date):'')+(state.place?' • '+state.place:''))+'</p>'+lineupHtmlTable(false)+'<p class="legend">Légende: 1B Premier but, 2B Deuxième but, 3B Troisième but, AC Arrêt-court, L1/L2 Lanceurs 🧢, BANC au banc, (#) rang de frappe.</p><h2>Vue terrain</h2>'+fieldHtmlSimple()+'</body></html>';openPrint(html)}
function lineupHtmlTable(inlineStyles){let a=active(),rankMaps=[];for(let i=0;i<state.innings;i++)rankMaps.push(new Map(batters(i).map(b=>[b.id,b.rank])));let h='<table'+(inlineStyles?' style="border-collapse:collapse;width:100%;font-family:Arial,sans-serif;font-size:13px"':'')+'><thead><tr><th>Ordre</th>';for(let i=0;i<state.innings;i++)h+='<th>Manche '+(i+1)+'</th>';h+='</tr></thead><tbody>';a.forEach((pl,ri)=>{h+='<tr><td>'+(ri+1)+'. '+esc(pl.name)+'</td>';for(let i=0;i<state.innings;i++){let po=state.schedule[i]?.pos[pl.id]||'BANC',r=rankMaps[i].get(pl.id);h+='<td>'+esc((po==='B'?'BANC':po)+(r?' (#'+r+')':''))+'</td>'}h+='</tr>'});return h+'</tbody></table>'}
function fieldHtmlSimple(){let boxes=defensePositionsByInning();return '<div class="fieldGrid">'+Object.entries(boxes).map(([title,arr])=>'<div class="box"><h3>'+esc(title)+'</h3><ol>'+arr.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol></div>').join('')+'</div>'}
function defensePositionsByInning(){let out={'Lanceurs 🧢':[],'1B — Premier but':[],'2B — Deuxième but':[],'3B — Troisième but':[],'AC — Arrêt-court':[]};for(let i=0;i<state.innings;i++){let items=defenseItems(i);out['Lanceurs 🧢'].push(items[0][1]);out['1B — Premier but'].push(items[1][1]);out['2B — Deuxième but'].push(items[2][1]);out['3B — Troisième but'].push(items[3][1]);out['AC — Arrêt-court'].push(items[4][1])}return out}
function copyEmailHtml(){let html='<div style="font-family:Arial,sans-serif;color:#162033"><h2>'+esc(state.team||'Équipe')+(state.opp?' vs '+esc(state.opp):'')+'</h2><p>'+esc((state.date?formatDate(state.date):'')+(state.place?' • '+state.place:''))+'</p><h3>Alignement</h3>'+lineupHtmlTable(true)+'<h3>Vue terrain</h3>'+fieldHtmlSimple()+'</div>';let text=exportText();if(navigator.clipboard&&window.ClipboardItem){let item=new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})});navigator.clipboard.write([item]).then(()=>modal('Copié','Le contenu HTML est prêt à coller dans Gmail.')).catch(()=>fallbackCopy(text))}else fallbackCopy(text)}
function fallbackCopy(text){navigator.clipboard?.writeText(text).then(()=>modal('Copié','Texte copié.')).catch(()=>modal('Copie impossible','Ton navigateur bloque le presse-papiers.'))}
function exportText(){let lines=[state.team||'Équipe'];if(state.opp)lines.push('vs '+state.opp);if(state.date)lines.push(formatDate(state.date));if(state.place)lines.push(state.place);lines.push('', 'Alignement');let a=active();for(let i=0;i<state.innings;i++)lines.push('Manche '+(i+1)+': '+batters(i).map(b=>b.rank+'. '+b.name).join(', '));return lines.join('\n')}
function openPrint(html){let w=window.open('','_blank');if(!w){modal('Fenêtre bloquée','Autorise les fenêtres surgissantes pour ouvrir la page prête à imprimer.');return}w.document.open();w.document.write(html);w.document.close()}
function downloadFile(name,content,type){downloadBlob(name,new Blob([content],{type:type||'text/plain'}))}
function downloadBlob(name,blob){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function loadExample(){let names=['Émile','Julien','Noah','Thomas','Olivier','Félix','William','Jacob','Samuel','Logan'];state=defaults();state.team='Expos de Montréal';state.opp='Padres de San Diego';state.date=new Date().toISOString().slice(0,10);state.place='Parc Ahuntsic — Terrain 2';state.side='locale';state.players=names.map(n=>({id:uid(),name:n,on:true}));state.order=state.players.map(p=>p.id);state.innings=4;state.schedule=[];save();generateAll();location.hash='#alignement'}
function shuffle(){let arr=active().map(p=>p.id);for(let i=arr.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}let inactive=state.order.filter(id=>!arr.includes(id));state.order=arr.concat(inactive);save();renderAll()}
function bind(){window.addEventListener('hashchange',()=>route());['team','opp','date','place','fixed'].forEach(id=>$('#'+id).addEventListener('input',()=>{updateFromInputs();renderAll()}));$$('[data-side]').forEach(b=>b.onclick=()=>{state.side=b.dataset.side;save();renderAll()});$('#addNames').onclick=()=>{let raw=$('#names').value.replace(/\\n/g,'\n');let names=raw.split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean);let existing=new Set(state.players.map(p=>p.name.toLowerCase()));names.forEach(n=>{if(!existing.has(n.toLowerCase())){let pl={id:uid(),name:n,on:true};state.players.push(pl);state.order.push(pl.id);existing.add(n.toLowerCase())}});$('#names').value='';save();renderAll()};$('#exampleBtn').onclick=loadExample;$('#goAlignBtn').onclick=()=>location.hash='#alignement';$('#shuffleBtn').onclick=shuffle;$('#regenBtn').onclick=generateAll;$('#copyHtmlBtn').onclick=copyEmailHtml;$('#printCoachBtn').onclick=printCoach;$('#parentImageBtn').onclick=exportParentImage;$('#parentImageBtn2').onclick=exportParentImage;$('#exportMatchBtn').onclick=exportMatchHtml;$('#exportMatchBtn2').onclick=exportMatchHtml;$('#matchPrev').onclick=()=>setMatchIndex(matchIndex-1);$('#matchNext').onclick=()=>setMatchIndex(matchIndex+1);$('#hamb').onclick=()=>$('#nav').classList.toggle('open');$('#resetBtn').onclick=()=>confirmModal('Réinitialiser','Effacer toutes les données locales et retourner à l’étape 1?',()=>{localStorage.removeItem(KEY);state=defaults();location.hash='#equipe';renderAll()});document.addEventListener('keydown',e=>{if(state.route==='match'){if(e.key==='ArrowRight')setMatchIndex(matchIndex+1);if(e.key==='ArrowLeft')setMatchIndex(matchIndex-1)}});$('#matchCard').addEventListener('touchstart',e=>{touchStartX=e.touches[0].clientX},{passive:true});$('#matchCard').addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-touchStartX;if(Math.abs(dx)>45)setMatchIndex(matchIndex+(dx<0?1:-1))},{passive:true});$('#modalOverlay').addEventListener('click',e=>{if(e.target.id==='modalOverlay')closeModal()})}
bind();ensureSchedule();renderAll();if(!location.hash)location.hash='#equipe';
})();
